In [14]:
import numpy as np
a=np.arange(18)
b=np.array([221,442123,345443,454657,773])
print(a)
print("Reshaped Array:\n",a.reshape(2,9))
print('\n'"For Array B")
print("Original Array:",b)
print("Sorted Array:",np.sort(b))
print("Indices of the sorted array are:",np.argsort(b))
print("Index of highest value function:",np.argmax(b))
print("Index of Shortest element:",np.argmin(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
Reshaped Array:
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]

For Array B
Original Array: [   221 442123 345443 454657    773]
Sorted Array: [   221    773 345443 442123 454657]
Indices of the sorted array are: [0 4 2 1 3]
Index of highest value function: 3
Index of Shortest element: 0
