In [ ]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1.sum(axis=0)) # Addition of all elements column wise
print(arr1.sum(axis=1)) # Addition of all elements row wise
print('\n')
arr2=np.array([[7,8,9],[2,8,0]])
print("Dot Product of 2 metrices:\n",np.dot(arr1,arr2.transpose())) 
print('\n')
print("Cross Product of 2 matrices:\n",np.cross(arr1,arr2))

[5 7 9]
[ 6 15]


Dot Product of 2 metrices:
 [[ 50  18]
 [122  48]]


Cross Product of 2 matrices:
 [[ -6  12  -6]
 [-48  12  22]]


In [18]:
import numpy as np
arr=np.array([13,18,2,81,-1])
print(np.sort(arr))
print(arr)
arr2=np.array([[-8,10,2,34,88],[5,4,3,2,1]])
print(np.sort(arr2,axis=0))

[-1  2 13 18 81]
[13 18  2 81 -1]
[[-8  4  2  2  1]
 [ 5 10  3 34 88]]
