In [14]:
import numpy as np 
arr=np.array([1,2,3,4,5]) #1D array 
arr2=np.array([[1,2,3],[4,5,6]]) #2D Array 
print(arr2[0][1])
print(arr)
#attributes of Numpy
print(arr2.shape) #returns the shape of array
print(arr2.dtype) #returns the data type of array
print(np.zeros(4)) #creates a 2-D array of zeroes
print('\n')
print(np.ones((5,5)))


2
[1 2 3 4 5]
(2, 3)
int64
[0. 0. 0. 0.]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
