In [12]:
import numpy as np
a1=np.random.rand(5,5)
print("Original Array:\n",a1,'\n')
Mask=a1<0.5
a1[Mask]=1
print("Masked Array:\n",a1,'\n')
print("Reshaped Array:\n",a1.reshape(1,25))
print(np.mean(a1,axis=1))

Original Array:
 [[0.36407701 0.88397108 0.46814413 0.30733828 0.01064109]
 [0.02403808 0.1728135  0.31678968 0.4152187  0.15086014]
 [0.96837623 0.77413131 0.69993633 0.5305998  0.52002012]
 [0.00154461 0.20962729 0.56251299 0.83362682 0.82107448]
 [0.5809242  0.01077927 0.3497963  0.64880458 0.03721154]] 

Masked Array:
 [[1.         0.88397108 1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.96837623 0.77413131 0.69993633 0.5305998  0.52002012]
 [1.         1.         0.56251299 0.83362682 0.82107448]
 [0.5809242  1.         1.         0.64880458 1.        ]] 

Reshaped Array:
 [[1.         0.88397108 1.         1.         1.         1.
  1.         1.         1.         1.         0.96837623 0.77413131
  0.69993633 0.5305998  0.52002012 1.         1.         0.56251299
  0.83362682 0.82107448 0.5809242  1.         1.         0.64880458
  1.        ]]
[0.97679422 1.         0.69861276 0.84344286 0.84594576]
