In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler 
df=pd.read_csv(r'C:\Users\KIIT0001\Desktop\Python Practice\CSV\student_marks.csv')
m=MinMaxScaler()
#dataf=np.array([df['English'],df['Maths']])
#print(dataf)
print(df['Maths'])
print(np.sort(df['Maths'],kind='mergesort'))
Normalized_marks=m.fit_transform(df[['Maths']]).round(2)
print(Normalized_marks)

[[87 64 76 63 46 89 58 56 75 83]
 [55 75 25 78 58 45 55 54 55 96]]
0    55
1    75
2    25
3    78
4    58
5    45
6    55
7    54
8    55
9    96
Name: Maths, dtype: int64
[25 45 54 55 55 55 58 75 78 96]
[[0.42]
 [0.7 ]
 [0.  ]
 [0.75]
 [0.46]
 [0.28]
 [0.42]
 [0.41]
 [0.42]
 [1.  ]]
